language: c

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - expect
      - gdb
      - apport

script:
  - export LD_PRELOAD=libSegFault.so
  - export SEGFAULT_USE_ALTSTACK=1
  - export LIBC_FATAL_STDERR_=1
  - ulimit -c unlimited
  - ulimit -a; ulimit -aH
  - ./configure
  - make
  - src/watchdog/io-watchdog foo

after_failure:
  - grep .  /etc/apport/*
  - grep .  /etc/apport/*/*
  - cat /usr/share/apport/apport
  - cat /proc/sys/kernel/core_pattern
  - ls -l /usr/share/apport/apport
  - find / -name '*core'
  - sh ./backtrace-all.sh
