language: c

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - expect
      - gdb
      - apport

script:
  - ulimit -c unlimited
  - ./configure
  - make
  - src/watchdog/io-watchdog foo

after_failure:
  - sh ./backtrace-all.sh
