language: c

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - expect
      - gdb
      - apport

script:
  - export LD_PRELOAD=libSegFault.so
  - export SEGFAULT_USE_ALTSTACK=1
  - export LIBC_FATAL_STDERR_=1
  - ulimit -c unlimited
  - ./configure
  - make
  - src/watchdog/io-watchdog foo

after_failure:
  - dmesg | grep Core
  - cat /proc/sys/kernel/core_pattern
  - sh ./backtrace-all.sh
