#!/bin/sh
##
# $Id: bootstrap 725 2006-03-14 17:02:28Z grondo $
##

set -x
aclocal -I config || exit 1
libtoolize --automake --copy --force || exit 1
autoheader || exit 1
automake --add-missing --copy --foreign || exit 1
autoconf --force --warnings=all || exit 1
rm -fr autom4te*.cache
exit 0

