#!/bin/sh
. ${SRCDIR}/functions
[ -n "$IO_WATCHDOG_TIMEOUT" ] ||  die "Failed. IO_WATCHDOG_TIMEOUT not set."
[ -n "$IO_WATCHDOG_PID" ] ||      die "Failed. IO_WATCHDOG_PID not set."
[ -n "$IO_WATCHDOG_TARGET" ] ||   die "Failed. IO_WATCHDOG_TARGET not set."

log_msg "PID $IO_WATCHDOG_PID ($IO_WATCHDOG_TARGET) exited after ${IO_WATCHDOG_TIMEOUT}s."
log_msg "Success."

kill $IO_WATCHDOG_PID

